<template>
    <div>
        <top-title :title="title"/>
    </div>
</template>
<script>
import TopTitle from 'components/content/TopTitle/TopTitle'
export default {
    name:'songs',
    components:{
        TopTitle
    },
    data(){
        return{
            title:[
                {
                    title:'发现音乐',
                    path:'/songs',
                    child:[
                        {
                            title:'推荐',
                            path:'/recommend'
                        },
                        {
                            title:'排行榜',
                            path:'/recommend'
                        },
                        {
                            title:'歌单',
                            path:'/recommend'
                        },
                        {
                            title:'主播电台',
                            path:'/recommend'
                        }
                    ]
                },
                {
                    title:'我的音乐',
                    path:'/mysongs'
                },
                {
                    title:'朋友',
                    path:'/friends'
                }
            ]
        }
    }
}
    
</script>